/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package EventDriven;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Angelo Javier
 */
public class AddToQueue extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddToQueue.class.getName());

    ResultSet rs;
    Connection conn;
    PreparedStatement ps;

    String userId;
    String name;
    String patientId;

    ImageIcon imageIcon = new ImageIcon(getClass().getResource("/image/Icon.png"));
    Image iconImage = imageIcon.getImage();

    AdminForm admin = new AdminForm("");

    /**
     * Creates new form NewJDialog
     */
    public AddToQueue(java.awt.Frame parent, boolean modal, String userId, String patientId, String name) {
        super(parent, modal);
        initComponents();
        this.setIconImage(iconImage);
        this.setLocationRelativeTo(null);
        this.setTitle("Records: " + patientId);

        this.userId = userId;
        this.patientId = patientId;
        this.name = name;
        conn = Database.sqlConnect();
        loadServices();
    }

    private void loadServices() {
        try {
            serviceComboBox.removeAllItems();
            serviceComboBox.addItem("Select Service");

            ps = conn.prepareStatement("SELECT ServiceName FROM Service");
            rs = ps.executeQuery();

            while (rs.next()) {
                String serviceName = rs.getString("ServiceName");
                serviceComboBox.addItem(serviceName);
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e);
        }
    }

    public void setLabel(String date) {
        patientLabel.setText("Patient: " + name + "  Date: " + date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        serviceLabel = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        serviceLabel1 = new javax.swing.JLabel();
        doctorComboBox = new javax.swing.JComboBox<>();
        serviceComboBox = new javax.swing.JComboBox<>();
        addQueue = new javax.swing.JButton();
        bookValidator = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        serviceLabel.setText("Doctor :");
        jPanel1.add(serviceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        patientLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(patientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 380, 30));

        serviceLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        serviceLabel1.setText("Service :");
        jPanel1.add(serviceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        doctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Doctor --", "Dr. Angelo", "Dr. Ageo", "Dr. Jet", "Dr. Leigh" }));
        jPanel1.add(doctorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 280, 30));

        serviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Service --" }));
        jPanel1.add(serviceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 280, 30));

        addQueue.setBackground(new java.awt.Color(0, 204, 0));
        addQueue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addQueue.setForeground(new java.awt.Color(255, 255, 255));
        addQueue.setText("Add to Queue");
        addQueue.addActionListener(this::addQueueActionPerformed);
        jPanel1.add(addQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 30));

        bookValidator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(bookValidator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 370, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 260));

        jPanel2.setBackground(new java.awt.Color(54, 54, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Walk-in Booking");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQueueActionPerformed
        String selectedService = (String) serviceComboBox.getSelectedItem();
        String selectedDoctor = (String) doctorComboBox.getSelectedItem();

        if (serviceComboBox.getSelectedIndex() == 0 || doctorComboBox.getSelectedIndex() == 0) {
            bookValidator.setForeground(Color.red);
            bookValidator.setText("Please select both a Service and a Doctor.");
            return;
        }

        int cleanPatientId = Integer.parseInt(patientId.replace("P-", ""));

        try {
            int nextQueueNum = 1;
            String sqlMax = "SELECT MAX(QueueNumber) FROM QueueBoard";
            ps = conn.prepareStatement(sqlMax);
            rs = ps.executeQuery();
            if (rs.next()) {
                nextQueueNum = rs.getInt(1) + 1;
            }

            String sqlInsert = "INSERT INTO QueueBoard (QueueNumber, PatientID, PatientName, Service, Doctor, Status) VALUES (?, ?, ?, ?, ?, ?)";
            ps = conn.prepareStatement(sqlInsert);

            ps.setInt(1, nextQueueNum);
            ps.setInt(2, cleanPatientId);
            ps.setString(3, name);
            ps.setString(4, selectedService);
            ps.setString(5, selectedDoctor);
            ps.setString(6, "Waiting");

            int result = ps.executeUpdate();
            if (result > 0) {
                StaffForm.patientValidator.setForeground(Color.green);
                StaffForm.patientValidator.setText("Patient " + patientId + " successfully added to the queue");
                admin.addReport(userId, "Add Patient to Queue", "Patient " + patientId + "added to the queue");
                this.dispose();
            }
        } catch (SQLException e) {
            System.out.println("" + e);
        } catch (NullPointerException e) {
            System.out.println("" + e);
        }
    }//GEN-LAST:event_addQueueActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQueue;
    private javax.swing.JLabel bookValidator;
    private javax.swing.JComboBox<String> doctorComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JComboBox<String> serviceComboBox;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JLabel serviceLabel1;
    // End of variables declaration//GEN-END:variables
}
