/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package EventDriven;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angelo Javier
 */
public class Consultation extends javax.swing.JDialog {

    ResultSet rs;
    Connection conn;
    PreparedStatement ps;

    private String userId;
    private String patientID;
    private String patientName;
    private String selectedService;
    private String selectedDoctor;

    ImageIcon imageIcon = new ImageIcon(getClass().getResource("/image/Icon.png"));
    Image iconImage = imageIcon.getImage();
    private TableRowSorter<DefaultTableModel> sorter;
    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    DefaultTableModel model;

    AdminForm admin = new AdminForm("");

    /**
     * Creates new form Consultation
     */
    public Consultation(java.awt.Frame parent, boolean modal, String userId, String id, String name, String service, String doctor) {
        super(parent, modal);
        initComponents();
        conn = Database.sqlConnect();
        this.setIconImage(iconImage);
        this.setLocationRelativeTo(null);

        this.userId = userId;
        this.patientID = id;
        this.patientName = name;
        this.selectedService = service;
        this.selectedDoctor = doctor;
        this.setTitle("Consulting: " + this.patientID);
        label.setText("Patient: " + patientName);
        this.model = (DefaultTableModel) prescriptionTable.getModel();
        center.setHorizontalAlignment(JLabel.CENTER);

        setUpTable();
        loadSuppliesCombo();
    }

    private void setUpTable() {
        DefaultTableModel dm = (DefaultTableModel) prescriptionTable.getModel();
        sorter = new TableRowSorter<>(dm);
        prescriptionTable.setRowSorter(sorter);
        prescriptionTable.setRowHeight(25);
        prescriptionTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        prescriptionTable.getTableHeader().setBackground(Color.decode("#3C4753"));
        prescriptionTable.getTableHeader().setForeground(Color.WHITE);
        for (int i = 0; i < prescriptionTable.getColumnCount(); i++) {
            prescriptionTable.getColumnModel().getColumn(i).setCellRenderer(center);
        }
    }

    private void loadSuppliesCombo() {
        try {
            ps = conn.prepareStatement("SELECT SupplyID, BrandName, GenericName, Measurement, Category, Quantity, UnitCost FROM Supply WHERE Quantity > 0");
            rs = ps.executeQuery();

            supplyComboBox.removeAllItems();
            supplyComboBox.addItem("-- Select Supply --");
            while (rs.next()) {
                supplyComboBox.addItem(rs.getString("BrandName") + " | " + rs.getString("GenericName"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        diagnosisTextArea = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        diagnosisValidator = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionTable = new javax.swing.JTable();
        supplyValidator = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        supplyComboBox = new javax.swing.JComboBox<>();
        quantityField = new javax.swing.JTextField();
        updateSupply = new javax.swing.JButton();
        deleteSupply = new javax.swing.JButton();
        addSupplyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 575));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Prescription :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Diagnosis :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        diagnosisTextArea.setColumns(20);
        diagnosisTextArea.setLineWrap(true);
        diagnosisTextArea.setRows(5);
        jScrollPane4.setViewportView(diagnosisTextArea);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 660, 90));

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 90, 30));

        okButton.setBackground(new java.awt.Color(0, 153, 255));
        okButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(255, 255, 255));
        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);
        jPanel1.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 90, 30));

        diagnosisValidator.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(diagnosisValidator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 560, 30));

        headerPanel.setBackground(new java.awt.Color(54, 54, 54));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 590, 50));

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 80));

        prescriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand Name", "Generic Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prescriptionTable.getTableHeader().setReorderingAllowed(false);
        prescriptionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prescriptionTable);
        if (prescriptionTable.getColumnModel().getColumnCount() > 0) {
            prescriptionTable.getColumnModel().getColumn(0).setResizable(false);
            prescriptionTable.getColumnModel().getColumn(1).setResizable(false);
            prescriptionTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 660, 140));

        supplyValidator.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(supplyValidator, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 540, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Supply --" }));
        jPanel2.add(supplyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, 30));

        quantityField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, 30));

        updateSupply.setBackground(new java.awt.Color(255, 153, 0));
        updateSupply.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateSupply.setForeground(new java.awt.Color(255, 255, 255));
        updateSupply.setText("Update");
        updateSupply.addActionListener(this::updateSupplyActionPerformed);
        jPanel2.add(updateSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 90, 30));

        deleteSupply.setBackground(new java.awt.Color(255, 0, 0));
        deleteSupply.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteSupply.setForeground(new java.awt.Color(255, 255, 255));
        deleteSupply.setText("Delete");
        deleteSupply.addActionListener(this::deleteSupplyActionPerformed);
        jPanel2.add(deleteSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 90, 30));

        addSupplyButton.setBackground(new java.awt.Color(0, 204, 51));
        addSupplyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSupplyButton.setForeground(new java.awt.Color(255, 255, 255));
        addSupplyButton.setText("Add");
        addSupplyButton.addActionListener(this::addSupplyButtonActionPerformed);
        jPanel2.add(addSupplyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Supply :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Quantity :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 660, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String diagnosis = diagnosisTextArea.getText().trim();

        if (diagnosis.isEmpty()) {
            diagnosisValidator.setForeground(Color.red);
            diagnosisValidator.setText("Please fill in diagnosis field");
            supplyValidator.setText("");
            return;
        }

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < model.getRowCount(); i++) {
            sb.append(model.getValueAt(i, 0)).append(" ")
                    .append(model.getValueAt(i, 1)).append(" (x")
                    .append(model.getValueAt(i, 2)).append(")");
            if (i < model.getRowCount() - 1) {
                sb.append(", ");
            }
        }
        String prescription = sb.toString();

        try {
            String sql = "INSERT INTO PatientRecords (PatientID, Service, Doctor, Diagnosis, Prescription, Date) VALUES (?, ?, ?, ?, ?, CURDATE())";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(this.patientID.replace("P-", "")));
            ps.setString(2, this.selectedService);
            ps.setString(3, this.selectedDoctor);
            ps.setString(4, diagnosis);
            ps.setString(5, prescription);

            if (ps.executeUpdate() > 0) {
                String sqlStatus = "UPDATE QueueBoard SET Status = 'Billing' WHERE PatientID = ?";
                ps = conn.prepareStatement(sqlStatus);
                ps.setInt(1, Integer.parseInt(this.patientID.replace("P-", "")));
                ps.executeUpdate();

                StaffForm.queueValidator.setForeground(Color.green);
                StaffForm.queueValidator.setText("Consultation Complete. Patient " + this.patientID + " moved to Billing");
                admin.addReport(userId, "Consultation", "Consultation Complete for Patient " + this.patientID);
                this.dispose();
            }
        } catch (SQLException e) {
            System.out.println(e);
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void addSupplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplyButtonActionPerformed
        String selectedItem = (String) supplyComboBox.getSelectedItem();
        String quantityInput = quantityField.getText().trim();

        if (selectedItem == null || selectedItem.equals("-- Select Supply --") || quantityInput.isEmpty()) {
            supplyValidator.setForeground(Color.RED);
            supplyValidator.setText("Selection in Supply Combo Box and quantity are required");
            diagnosisValidator.setText("");
            return;
        }

        try {
            int qtyRequested = Integer.parseInt(quantityInput);

            String[] parts = selectedItem.split(" \\| ");
            if (parts.length < 2) {
                return;
            }
            String brandName = parts[0];
            String genericName = parts[1];

            ps = conn.prepareStatement("SELECT Quantity FROM Supply WHERE BrandName = ? AND GenericName = ?");
            ps.setString(1, brandName);
            ps.setString(2, genericName);
            rs = ps.executeQuery();

            if (rs.next()) {
                int stockAvailable = rs.getInt("Quantity");
                int existingRow = -1;

                for (int i = 0; i < model.getRowCount(); i++) {
                    if (model.getValueAt(i, 0).equals(brandName) && model.getValueAt(i, 1).equals(genericName)) {
                        existingRow = i;
                        break;
                    }
                }

                if (existingRow != -1) {
                    int currentTableQty = Integer.parseInt(model.getValueAt(existingRow, 2).toString());
                    if ((currentTableQty + qtyRequested) > stockAvailable) {
                        supplyValidator.setForeground(Color.red);
                        supplyValidator.setText("Stock available is only " + stockAvailable);
                        diagnosisValidator.setText("");
                        return;
                    } else {
                        model.setValueAt(currentTableQty + qtyRequested, existingRow, 2);
                        supplyValidator.setForeground(Color.green);
                        supplyValidator.setText(brandName + " updated");
                        diagnosisValidator.setText("");
                    }
                } else {
                    if (qtyRequested > stockAvailable) {
                        supplyValidator.setForeground(Color.red);
                        supplyValidator.setText("Stock available is only " + stockAvailable);
                        diagnosisValidator.setText("");
                        return;
                    } else {
                        model.addRow(new Object[]{brandName, genericName, qtyRequested});
                        supplyValidator.setForeground(Color.green);
                        supplyValidator.setText(brandName + " added.");
                        diagnosisValidator.setText("");
                    }
                }
                quantityField.setText("");
                supplyComboBox.setSelectedIndex(0);
            }
        } catch (NumberFormatException e) {
            supplyValidator.setForeground(Color.RED);
            supplyValidator.setText("Quantity must be a valid number");
            diagnosisValidator.setText("");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_addSupplyButtonActionPerformed

    private void prescriptionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionTableMouseClicked
        int selectedRow = prescriptionTable.getSelectedRow();

        if (selectedRow != -1) {
            int modelRow = prescriptionTable.convertRowIndexToModel(selectedRow);

            String brand = model.getValueAt(modelRow, 0).toString();
            String generic = model.getValueAt(modelRow, 1).toString();
            String qty = model.getValueAt(modelRow, 2).toString();

            String fullItemName = brand + " | " + generic;

            supplyComboBox.setSelectedItem(fullItemName);
            quantityField.setText(qty);
        }
    }//GEN-LAST:event_prescriptionTableMouseClicked

    private void updateSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplyActionPerformed
        int selectedRow = prescriptionTable.getSelectedRow();

        if (selectedRow == -1) {
            supplyValidator.setForeground(Color.RED);
            supplyValidator.setText("Please select an item from the table to update");
            diagnosisValidator.setText("");
            return;
        }

        String selectedItem = (String) supplyComboBox.getSelectedItem();
        String quantityInput = quantityField.getText().trim();

        if (selectedItem == null || selectedItem.equals("-- Select Supply --") || quantityInput.isEmpty()) {
            supplyValidator.setForeground(Color.RED);
            supplyValidator.setText("Selection in Supply Combo Box and quantity are required");
            diagnosisValidator.setText("");
            return;
        }

        try {
            int newQty = Integer.parseInt(quantityInput);
            int modelRow = prescriptionTable.convertRowIndexToModel(selectedRow);

            String[] parts = selectedItem.split(" \\| ");
            String brandName = parts[0];
            String genericName = parts[1];

            ps = conn.prepareStatement("SELECT Quantity FROM Supply WHERE BrandName = ? AND GenericName = ?");
            ps.setString(1, brandName);
            ps.setString(2, genericName);
            rs = ps.executeQuery();

            if (rs.next()) {
                int stockAvailable = rs.getInt("Quantity");
                if (newQty > stockAvailable) {
                    supplyValidator.setForeground(Color.RED);
                    supplyValidator.setText("Invalid update. Only " + stockAvailable + " in stock");
                    diagnosisValidator.setText("");
                } else {
                    model.setValueAt(brandName, modelRow, 0);
                    model.setValueAt(genericName, modelRow, 1);
                    model.setValueAt(newQty, modelRow, 2);

                    supplyValidator.setForeground(Color.green);
                    supplyValidator.setText("Prescription updated");
                    diagnosisValidator.setText("");

                    quantityField.setText("");
                    supplyComboBox.setSelectedIndex(0);
                    prescriptionTable.clearSelection();
                }
            }
        } catch (NumberFormatException e) {
            supplyValidator.setForeground(Color.RED);
            supplyValidator.setText("Quantity must be a valid number");
            diagnosisValidator.setText("");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_updateSupplyActionPerformed

    private void deleteSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplyActionPerformed
        // TODO add your handling code here:
        int selectedRow = prescriptionTable.getSelectedRow();

        if (selectedRow == -1) {
            supplyValidator.setForeground(Color.RED);
            supplyValidator.setText("Select an item in the table to remove.");
            diagnosisValidator.setText("");
            return;
        }

        int modelRow = prescriptionTable.convertRowIndexToModel(selectedRow);
        String brand = model.getValueAt(modelRow, 0).toString();

        model.removeRow(modelRow);

        supplyValidator.setForeground(Color.GREEN);
        supplyValidator.setText(brand + " removed");
        diagnosisValidator.setText("");

        quantityField.setText("");
        supplyComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_deleteSupplyActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteSupply;
    private javax.swing.JTextArea diagnosisTextArea;
    private javax.swing.JLabel diagnosisValidator;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label;
    private javax.swing.JButton okButton;
    private javax.swing.JTable prescriptionTable;
    private javax.swing.JTextField quantityField;
    private javax.swing.JComboBox<String> supplyComboBox;
    private javax.swing.JLabel supplyValidator;
    private javax.swing.JButton updateSupply;
    // End of variables declaration//GEN-END:variables
}
