/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package EventDriven;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.SQLException;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Angelo Javier
 */
public class PatientHistory extends javax.swing.JDialog {

    ResultSet rs;
    Connection conn;
    PreparedStatement ps;
    DefaultTableCellRenderer center = new DefaultTableCellRenderer();

    ImageIcon imageIcon = new ImageIcon(getClass().getResource("/image/Icon.png"));
    Image iconImage = imageIcon.getImage();
    private TableRowSorter<DefaultTableModel> sorter;
    private String currentPatientId;

    /**
     * Creates new form PatientHistory
     */
    public PatientHistory(java.awt.Frame parent, boolean modal, String patientId) {
        super(parent, modal);
        initComponents();
        this.setIconImage(iconImage);
        this.setLocationRelativeTo(null);
        this.setTitle("Records: " + patientId);
        this.currentPatientId = patientId;
        conn = Database.sqlConnect();
        center.setHorizontalAlignment(JLabel.CENTER);
        jLabel1.setText("Patient: " + patientId + " History");

        try {
            int idValue = Integer.parseInt(patientId.replace("P-", ""));
            loadPatientRecords(idValue);
        } catch (NumberFormatException e) {
            System.out.println("Error: " + e);
        }

        setUpHistoryTable();
    }

    private void loadPatientRecords(int cleanId) {
        try {
            ps = conn.prepareStatement("SELECT RecordID, Service, Doctor, Diagnosis, Prescription, Date "
                    + "FROM PatientRecords WHERE PatientID = ? ORDER BY Date DESC");
            ps.setInt(1, cleanId);
            rs = ps.executeQuery();

            DefaultTableModel dm = (DefaultTableModel) historyTable.getModel();
            dm.setRowCount(0);

            while (rs.next()) {
                Vector<Object> v1 = new Vector<>();
                v1.add(rs.getInt("RecordID"));
                v1.add(rs.getString("Service"));
                v1.add(rs.getString("Doctor"));
                v1.add(rs.getString("Diagnosis"));
                v1.add(rs.getString("Prescription"));
                v1.add(rs.getDate("Date"));
                dm.addRow(v1);
            }

        } catch (SQLException e) {
            System.out.println("" + e);
        }
    }

    private void setUpHistoryTable() {
        DefaultTableModel dm = (DefaultTableModel) historyTable.getModel();
        sorter = new TableRowSorter<>(dm);
        historyTable.setRowSorter(sorter);
        historyTable.setRowHeight(25);
        historyTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        historyTable.getTableHeader().setBackground(Color.decode("#3C4753"));
        historyTable.getTableHeader().setForeground(Color.WHITE);
        for (int i = 0; i < historyTable.getColumnCount(); i++) {
            historyTable.getColumnModel().getColumn(i).setCellRenderer(center);
        }
        historyTable.getColumnModel().getColumn(3).setCellRenderer(new TextAreaRenderer());
        historyTable.getColumnModel().getColumn(4).setCellRenderer(new TextAreaRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        printPatientHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printPatientHistory.setBackground(new java.awt.Color(0, 153, 153));
        printPatientHistory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printPatientHistory.setForeground(new java.awt.Color(255, 255, 255));
        printPatientHistory.setText("Print Patient History");
        printPatientHistory.setFocusable(false);
        printPatientHistory.addActionListener(this::printPatientHistoryActionPerformed);
        jPanel1.add(printPatientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 5, 210, 30));

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RecordID", "Service", "Doctor", "Diagnosis/Notes", "Prescription", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(historyTable);
        if (historyTable.getColumnModel().getColumnCount() > 0) {
            historyTable.getColumnModel().getColumn(0).setResizable(false);
            historyTable.getColumnModel().getColumn(1).setResizable(false);
            historyTable.getColumnModel().getColumn(2).setResizable(false);
            historyTable.getColumnModel().getColumn(3).setResizable(false);
            historyTable.getColumnModel().getColumn(4).setResizable(false);
            historyTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 980, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 430));

        jPanel2.setBackground(new java.awt.Color(54, 54, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient : History");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 350, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPatientHistoryActionPerformed
        // TODO add your handling code here:

        try {
            int cleanId = Integer.parseInt(this.currentPatientId.replace("P-", ""));
            HashMap<String, Object> parameters = new java.util.HashMap<>();
            ps = conn.prepareStatement("SELECT FirstName, LastName, Sex, Age, Weight, Height, ContactNumber "
                    + "FROM Patient WHERE PatientID = ?");
            ps.setInt(1, cleanId);
            rs = ps.executeQuery();

            if (rs.next()) {
                parameters.put("pName", rs.getString("FirstName") + " " + rs.getString("LastName"));
                parameters.put("pSex", rs.getString("Sex"));
                parameters.put("pAge", rs.getInt("Age"));
                parameters.put("pWeight", rs.getDouble("Weight"));
                parameters.put("pHeight", rs.getDouble("Height"));
                parameters.put("pContact", rs.getString("ContactNumber"));
                parameters.put("patientId", cleanId);
            }
            JasperReport patientReport = (JasperReport) JRLoader.loadObjectFromFile("src\\reports\\PatientHistory.jasper");
            JasperPrint reportPrint = JasperFillManager.fillReport(patientReport, parameters, conn);
            JasperViewer viewer = new JasperViewer(reportPrint, false);
            javax.swing.JDialog reportDialog = new javax.swing.JDialog(this, "Print Preview", true);
            reportDialog.setContentPane(viewer.getContentPane());
            reportDialog.setSize(1000, 900);
            reportDialog.setLocationRelativeTo(this);
            reportDialog.setVisible(true);

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_printPatientHistoryActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printPatientHistory;
    // End of variables declaration//GEN-END:variables
}
